export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA'
export const CREATE_PLAYER = 'CREATE_PLAYER'
export const FETCH_PLAYERS_LIST = 'FETCH_PLAYERS_LIST'
export const UPDATE_TEAM_PLAYER = 'UPDATE_TEAM_PLAYER'